workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "TuProyecto.xcworkspace"
        XCODE_SCHEME: "TuEsquema"
    integrations:
      app_store_connect:
        auth: integration  # Definir autenticación para la integración
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Instalar dependencias
        script: |
          pod install
      - name: Compilar proyecto
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_STYLE=Automatic
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      app_store_connect:
        auth: integration  # Usar integración de App Store Connect
        submit_to_testflight: true
