integrations:
  app_store_connect:
    auth: integration

workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "TuProyecto.xcworkspace"
        XCODE_SCHEME: "TuEsquema"
    scripts:
      - name: Instalar dependencias
        script: |
          pod install
      - name: Compilar proyecto
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_STYLE=Automatic
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
